Shell sort
becurrie/py-custom-sorters pull request #3
Opened 2019-10-01 16:45 UTC by underhood31

Added new sorting algorithm: shell-sort.

2019-11-02 17:00 UTC, becurrie requested changes
Hey! Great addition of a new sort method, just some tiny syntactical changes and I'd be happy to merge! 👍

2019-11-02 17:00 UTC, becurrie commented on README.md
> +- [argparse](https://docs.python.org/3.6/library/argparse.html)
What changed here exactly?

2019-11-02 17:00 UTC, becurrie commented on py_sorter/sorter.py
> +                                        'insertion_recursive', 'heap','shell'],
Use consistent format in regards to any commas in lists.

```suggestion
                                        'insertion_recursive', 'heap', 'shell'],
```

2019-11-02 17:00 UTC, becurrie commented on py_sorter/sorter.py
> +    elif args.sort=='shell':
```suggestion
    elif args.sort == 'shell':
```

2019-11-02 17:00 UTC, becurrie commented on py_sorter/sorter.py
> +        sorted_list=shell_sort(original_list)
```suggestion
        sorted_list = shell_sort(original_list)
```

2019-11-02 17:00 UTC, becurrie commented on py_sorter/sorts.py
> +    We keep reducing the value of h until it becomes 1. """
end of docstrings should be underneath the explanation.

```suggestion
    We keep reducing the value of h until it becomes 1.
    """
```

2019-11-04 07:33 UTC, underhood31 commented on README.md
> +- [argparse](https://docs.python.org/3.6/library/argparse.html)
Nothing was intended here. Maybe some white space.

2019-11-04 11:34 UTC, becurrie approved these changes
Changes look good, approving 👍

2019-11-04 11:34 UTC, merged